<?php
session_start();
require_once '../includes/db.php';

// 1. Authenticate (Security)
if (!isset($_SESSION['user_id'])) {
    die("Unauthorized access.");
}

// 2. Fetch Data for the Current Month
$month_name = date('F Y');
$month = date('m');
$year = date('Y');

$query = "SELECT type, SUM(amount) as total FROM finances WHERE MONTH(transaction_date) = ? AND YEAR(transaction_date) = ? GROUP BY type";
$stmt = $db->prepare($query);
$stmt->execute([$month, $year]);
$results = $stmt->fetchAll(PDO::FETCH_KEY_PAIR);

// Ensure all categories are represented
$categories = ['tithe'=>0, 'offering'=>0, 'donation'=>0, 'mission'=>0, 'thanksgiving'=>0, 'expense'=>0];
foreach($results as $type => $total) { $categories[$type] = $total; }

$totalIncome = array_sum(array_intersect_key($categories, array_flip(['tithe', 'offering', 'donation', 'mission', 'thanksgiving'])));
$totalExpenses = abs($categories['expense']);
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Financial_Report_<?= $month_name ?></title>
    <style>
        body { font-family: 'Segoe UI', Arial, sans-serif; color: #333; line-height: 1.6; padding: 40px; }
        .header { text-align: center; border-bottom: 2px solid #3b82f6; padding-bottom: 20px; margin-bottom: 30px; }
        .report-title { font-size: 24px; font-weight: bold; color: #1e3a8a; margin: 0; }
        .meta { color: #64748b; font-size: 14px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f8fafc; text-align: left; padding: 12px; border-bottom: 2px solid #e2e8f0; }
        td { padding: 12px; border-bottom: 1px solid #f1f5f9; }
        .total-row { font-weight: bold; background: #eff6ff; }
        .footer { margin-top: 50px; font-size: 12px; text-align: center; color: #94a3b8; }
        @media print {
            .no-print { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; background: #3b82f6; color: white; border: none; border-radius: 5px; cursor: pointer;">
            Click to Save as PDF
        </button>
        <button onclick="window.history.back()" style="padding: 10px 20px; background: #64748b; color: white; border: none; border-radius: 5px; cursor: pointer;">
            Go Back
        </button>
    </div>

    <div class="header">
        <h1 class="report-title">Monthly Financial Report</h1>
        <p class="meta">Period: <?= $month_name ?> | Generated by: <?= $_SESSION['full_name'] ?></p>
    </div>

    <h3>Income Breakdown</h3>
    <table>
        <thead>
            <tr>
                <th>Category</th>
                <th style="text-align: right;">Amount</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach(['tithe', 'offering', 'donation', 'mission', 'thanksgiving'] as $cat): ?>
            <tr>
                <td><?= ucfirst($cat) ?></td>
                <td style="text-align: right;">$<?= number_format($categories[$cat], 2) ?></td>
            </tr>
            <?php endforeach; ?>
            <tr class="total-row">
                <td>Total Monthly Income</td>
                <td style="text-align: right;">$<?= number_format($totalIncome, 2) ?></td>
            </tr>
        </tbody>
    </table>

    <h3 style="margin-top: 40px;">Expenditure & Balance</h3>
    <table>
        <tr>
            <td>Total Expenses</td>
            <td style="text-align: right; color: #dc2626;">-$<?= number_format($totalExpenses, 2) ?></td>
        </tr>
        <tr class="total-row">
            <td style="font-size: 18px;">Net Position</td>
            <td style="text-align: right; font-size: 18px; color: #16a34a;">$<?= number_format($totalIncome - $totalExpenses, 2) ?></td>
        </tr>
    </table>

    <div class="footer">
        <p>This is a computer-generated document from the Church Management System.</p>
        <p>Date Generated: <?= date('d/m/Y H:i:s') ?></p>
    </div>

    <script>
        // Trigger print dialog immediately if desired
        // window.print();
    </script>
</body>
</html>